<?php
/**
 * Created by PhpStorm.
 * User: xavi
 * Date: 17/05/18
 * Time: 13:55
 */

namespace App;


class NullAction extends AbstractAction
{
    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }
}